# Generated by Django 5.0.6 on 2024-05-13 16:08

import ckeditor_uploader.fields
import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان مقاله')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات')),
                ('created_date', django_jalali.db.models.jDateField(default=datetime.date(2024, 5, 13), verbose_name='تاریخ ساخت')),
                ('published_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('is_active', models.BooleanField(default=False, verbose_name='تایید/عدم تایید')),
                ('cover_image', models.ImageField(upload_to='media/article/', verbose_name='عکس مقاله')),
                ('cover_title', models.CharField(max_length=2000, verbose_name='عنوان عکس مقاله')),
                ('cover_alt', models.CharField(max_length=2000, verbose_name='متن جایگزین عکس')),
                ('slug', models.SlugField()),
            ],
        ),
    ]
