# Generated by Django 5.0.6 on 2024-05-18 12:30

import ckeditor_uploader.fields
import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان مقاله')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات')),
                ('created_date', django_jalali.db.models.jDateField(default=datetime.date(2024, 5, 18), verbose_name='تاریخ ساخت')),
                ('published_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('is_active', models.BooleanField(default=False, verbose_name='تایید/عدم تایید')),
                ('cover_image', models.ImageField(upload_to='media/article/', verbose_name='عکس مقاله')),
                ('cover_title', models.CharField(max_length=2000, verbose_name='عنوان عکس مقاله')),
                ('cover_alt', models.CharField(max_length=2000, verbose_name='متن جایگزین عکس')),
                ('slug', models.SlugField()),
                ('view_count', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('selected', models.BooleanField(default=False, verbose_name='منتخب')),
                ('top', models.BooleanField(default=False, verbose_name='تایید برای بالا صفحه')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='نام دسته بندی')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='blog/category/', verbose_name='تصویر دسته بندی')),
                ('picture_alt', models.CharField(blank=True, max_length=250, null=True, verbose_name='متن جایگزین')),
                ('picture_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان تصویر')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'دسته بندی مقاله',
                'verbose_name_plural': 'دسته بندی مقاله ها',
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان کامنت')),
                ('comment', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن کامنت')),
                ('created_date', django_jalali.db.models.jDateField(default=datetime.date(2024, 5, 18), verbose_name='تاریخ ساخت')),
                ('published_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('is_active', models.BooleanField(default=False, verbose_name='تایید/عدم تایید')),
            ],
            options={
                'verbose_name': 'کامنت مقاله',
                'verbose_name_plural': 'کامنت مقالات',
            },
        ),
        migrations.CreateModel(
            name='BlogSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('name', 'name'), ('property', 'property')], max_length=120)),
                ('title', models.CharField(max_length=2000)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'seo مقاله',
                'verbose_name_plural': 'seo مقاله',
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=2000, verbose_name='تگ مقاله')),
                ('is_active', models.BooleanField(default=False, verbose_name='تایید / عدم تایید')),
            ],
            options={
                'verbose_name': 'تگ مقاله',
                'verbose_name_plural': 'تگ مقالات',
            },
        ),
        migrations.CreateModel(
            name='CategorySeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('name', 'name'), ('property', 'property')], max_length=120)),
                ('title', models.CharField(max_length=2000)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'seo دسته بندی مقاله',
                'verbose_name_plural': 'seo دسته بندی مقاله',
            },
        ),
    ]
