# Generated by Django 5.0.6 on 2024-05-14 13:30

import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AddField(
            model_name='blog',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 5, 14), verbose_name='تاریخ ساخت'),
        ),
    ]
