# Generated by Django 5.0.6 on 2024-05-14 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_blog_options_blog_view_count_and_more'),
        ('Blog_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_category', to='Blog_category.blogcategory', verbose_name='دسته بندی'),
        ),
    ]
