# Generated by Django 5.0.6 on 2024-05-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='selected',
            field=models.BooleanField(default=False, verbose_name='منتخب'),
        ),
    ]
