# Generated by Django 5.0.6 on 2024-05-15 14:53

import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_blog_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='top',
            field=models.BooleanField(default=False, verbose_name='تایید برای بالا صفحه'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 5, 15), verbose_name='تاریخ ساخت'),
        ),
    ]
