# Generated by Django 5.0.6 on 2024-05-16 07:43

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_blog_top_alter_blog_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 5, 16), verbose_name='تاریخ ساخت'),
        ),
    ]
