# Generated by Django 5.0.6 on 2024-05-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('name', 'name'), ('property', 'property')], max_length=120)),
                ('title', models.CharField(max_length=2000)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'seo اصلی',
                'verbose_name_plural': 'seo اصلی',
            },
        ),
    ]
