# Generated by Django 5.0.6 on 2024-05-18 12:30

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان سایت')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='فاوآیکون')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='لوگوی سایت')),
                ('logo_url', models.CharField(max_length=250, null=True, verbose_name='url لوگو')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن')),
                ('logo_alt', models.CharField(blank=True, max_length=250, null=True, verbose_name='متن جایگزین لوگو')),
                ('logo_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان لوگو')),
                ('about_us', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='درباره ما')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='آدرس')),
                ('text_footer', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='متن پایین صفحه')),
                ('text_contact', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='متن تماس با ما')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام شبکه')),
                ('url', models.CharField(max_length=250, verbose_name='url شبکه')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='لوگوی شبکه')),
                ('logo_url', models.CharField(max_length=250, null=True, verbose_name='url لوگو')),
                ('logo_alt', models.CharField(blank=True, max_length=250, null=True, verbose_name='متن جایگزین لوگو')),
                ('logo_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان لوگو')),
            ],
            options={
                'verbose_name': 'شبکه های اجتماعی',
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
    ]
