# Generated by Django 5.0.6 on 2024-05-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_alt',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='متن جایگزین لوگو'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان لوگو'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='logo_alt',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='متن جایگزین لوگو'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='logo_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان لوگو'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='لوگوی شبکه'),
        ),
    ]
