# Generated by Django 5.0.6 on 2024-05-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_sitesettings_logo_alt_sitesettings_logo_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='logo_url',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
