# Generated by Django 5.0.6 on 2024-05-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_socialmedia_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_us',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='درباره ما'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='فاوآیکون'),
        ),
    ]
