# Generated by Django 5.0.6 on 2024-05-16 14:06

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_sitesettings_about_us_sitesettings_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='text_footer',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='متن پایین صفحه'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_us',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='درباره ما'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='لوگوی سایت'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان سایت'),
        ),
    ]
